language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1

before_install:
  - gem install bundler
  - sudo apt-get install -y build-essential libtool libxml2-dev libxslt-dev zlib1g-dev patch ruby-dev liblzma-dev
